meta:
  engine: 4.0.4
  name: acinonyx
  version: 0.1
  author: stronglytyped
  url: https://github.com/rdavison/acinonyx
units:
  kx: cx
  ky: cy
  ppx: 4
  ppy: 4
  px: kx + ppx
  py: ky + ppy
  brickw: 6.5 kx + ppx + 11
  brickh: 4.5 ky + ppy + 2
  brickx: 3
  bricky: -ky + 0
points:
  zones:
    matrix:
      rotate: 10
      key:
        spread: kx
        padding: ky
      columns:
        outer:
          key:
            stagger: 0 ky
            column_net: col_outer
            mirror.column_net: mirror_col_outer
        pinky:
          key:
            stagger: 0 ky
            column_net: col_pinky
            mirror.column_net: mirror_col_pinky
        ring:
          key:
            stagger: 0.5 ky
            splay: -5
            origin: [-kx/2, -ky/2]
            column_net: col_ring
            mirror.column_net: mirror_col_ring
        middle:
          key:
            stagger: 0.2 ky
            splay: -5
            origin: [-kx/2, -ky/2]
            column_net: col_middle
            mirror.column_net: mirror_col_middle
        index:
          key:
            stagger: -0.2 ky
            column_net: col_index
            mirror.column_net: mirror_col_index
        inner:
          key:
            stagger: -0.1 ky
            column_net: col_inner
            mirror.column_net: mirror_col_inner
      rows:
        bottom:
          row_net: row_bottom
          mirror.row_net: mirror_row_bottom
        home:
          row_net: row_home
          mirror.row_net: mirror_row_home
        top:
          row_net: row_top
          mirror.row_net: mirror_row_top
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-kx-kx/4, -1.1 ky]
        rotate: 4
      key:
        spread: kx
      columns:
        near:
          key:
            splay: 0
            origin: [-0.5 kx, -0.5 ky]
            column_net: col_middle
            mirror.column_net: mirror_col_middle
        home:
          key:
            splay: -17
            origin: [-0.5 kx, -0.5 ky]
            column_net: col_index
            mirror.column_net: mirror_col_index
        far:
          key:
            splay: -17
            origin: [-0.5 kx, -0.5 ky]
            column_net: col_inner
            mirror.column_net: mirror_col_inner
      rows:
        thumb:
          row_net: row_thumb
          mirror.row_net: mirror_row_thumb
  mirror: &mirror
    ref: thumbfan_far_thumb
    distance: 2.5kx
outlines:
  raw:
    - what: rectangle
      where: true
      asym: source
      size: [px, py]
      corner: ppx
  battery_l:
    - what: rectangle
      where:
        - ref: matrix_inner_home
          shift: [kx + 3, -0.80 ky]
      size: [20, 28.5]
      corner: 0
  battery_r:
    - what: rectangle
      where:
        - ref: mirror_matrix_inner_home
          shift: [kx + 3, -0.80 ky]
      size: [20, 28.5]
      corner: 0
  battery:
    - "battery_l"
    - "battery_r"
  brick:
    - what: rectangle
      where:
        - ref: matrix_middle_home
          shift: [brickx , bricky]
      size: [brickw, brickh]
      corner: 1
    - what: rectangle
      where:
        - ref: mirror_matrix_middle_home
          shift: [brickx , bricky]
      size: [brickw, brickh]
      corner: 1
  switches:
    - what: rectangle
      where: true
      asym: source
      size: 14
  keycaps:
    - what: rectangle 
      where: true
      asym: source
      size: [kx, ky] 
      corner: 2
  keywell:
    - "raw"
  base_outline:
    - "keywell"
    - "+brick"
  screw_holes:
    top_left:
      what: circle
      where:
        - ref: matrix_outer_top
          shift: [0.2 kx, 1.3 ky]
      radius: 1.05
    bottom_left:
      what: circle
      where:
        - ref: matrix_outer_bottom
          shift: [-0.55 kx, -1.05 ky]
      radius: 1.05
    top_right:
      what: circle
      where:
        - ref: matrix_inner_top
          shift: [1.65 kx, 0.56 ky]
      radius: 1.05
    thumb:
      what: circle
      where:
        - ref: matrix_inner_bottom
          shift: [1.65 kx, -1.9 ky]
      radius: 1.05
    mirror_top_left:
      what: circle
      where:
        - ref: mirror_matrix_outer_top
          shift: [0.2 kx, 1.3 ky]
      radius: 1.05
    mirror_bottom_left:
      what: circle
      where:
        - ref: mirror_matrix_outer_bottom
          shift: [-0.55 kx, -1.05 ky]
      radius: 1.05
    mirror_top_right:
      what: circle
      where:
        - ref: mirror_matrix_inner_top
          shift: [1.65 kx, 0.56 ky]
      radius: 1.05
    mirror_thumb:
      what: circle
      where:
        - ref: mirror_matrix_inner_bottom
          shift: [1.65 kx, -1.9 ky]
      radius: 1.05
  mounting_holes:
    $extends: outlines.screw_holes
    top_left:
      radius: 2.05
    bottom_left:
      radius: 2.05
    top_right:
      radius: 2.05
    thumb:
      radius: 2.05
    mirror_top_left:
      radius: 2.05
    mirror_bottom_left:
      radius: 2.05
    mirror_top_right:
      radius: 2.05
    mirror_thumb:
      radius: 2.05
  bottom_outline:
    - "base_outline"
    - "-screw_holes"
  plate:
    - "keywell"
    - "brick"
    #- "-keycaps"
    - "-switches"
    - "-screw_holes"
  pcb:
    - "base_outline"
    - "-mounting_holes"
pcbs:
  top_plate:
    outlines:
      edge:
        outline: plate
        layer: Edge.Cuts
    footprints:
      jlc_order_number:
        what: text
        where:
          ref:
            - matrix_ring_home
          shift: [-0.25 kx, 0.5 ky]
        params:
          text: "JLCJLCJLCJLC"
          justify: left
  bottom_plate:
    outlines:
      edge:
        outline: bottom_outline
        layer: Edge.Cuts
  board:
    outlines:
      keycaps:
        outline: keycaps
        layer: F.SilkS
      battery:
        outline: battery
        layer: F.SilkS
      edge:
        outline: pcb
        layer: Edge.Cuts
    footprints:
      choc_hotswap:
        what: choc
        where:
          - /matrix_.*/
          - /thumbfan_.*/
        params:
          hotswap: true
          reverse: false
          keycaps: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      diode:
        what: diode
        where:
          - /matrix_.*/
          - /thumbfan_.*/
        adjust.shift: [0, -5]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
      mcu_l:
        what: xiao
        where:
          ref:
            - matrix_inner_home
          shift: [1 kx + 3, 0.75 ky]
        params:
          P0: row_top
          P1: row_home
          P2: row_bottom
          P3: row_thumb
          P4: col_inner
          P5: col_index
          P6: col_middle
          P7: col_ring
          P8: col_pinky
          P9: col_outer
          P10: P10
          RAW5V: RAW5V
          GND: GND
          RAW3V3: RAW3V3
          SWCLK: SWCLK
          SWDIO: SWDIO
          RST: RST
          BAT_POS: BAT_POS
          BAT_NEG: BAT_NEG
          NFC0: NFC0
          NFC1: NFC1
      mcu_r:
        what: xiao
        where:
          ref:
            - mirror_matrix_inner_home
          shift: [1 kx + 3, 0.75 ky]
        params:
          P0: mirror_row_top
          P1: mirror_row_home
          P2: mirror_row_bottom
          P3: mirror_row_thumb
          P4: mirror_col_inner
          P5: mirror_col_index
          P6: mirror_col_middle
          P7: mirror_col_ring
          P8: mirror_col_pinky
          P9: mirror_col_outer
          P10: mirror_P10
          RAW5V: mirror_RAW5V
          GND: mirror_GND
          RAW3V3: mirror_RAW3V3
          SWCLK: mirror_SWCLK
          SWDIO: mirror_SWDIO
          RST: mirror_RST
          BAT_POS: mirror_BAT_POS
          BAT_NEG: mirror_BAT_NEG
          NFC0: mirror_NFC0
          NFC1: mirror_NFC1
      # mcu_l:
      #   what: promicro
      #   where:
      #     ref:
      #       - matrix_index_top
      #     shift: [20+kx, -11]
      #     rotate: 270
      #   params:
      #     orientation: up
      #     P4: row_top
      #     P5: row_home
      #     P6: row_bottom
      #     P7: row_thumb
      #     P14: col_inner
      #     P15: col_index
      #     P18: col_middle
      #     P19: col_ring
      #     P20: col_pinky
      #     P21: col_outer
      pad_plus_l:
        what: pad
        where:
          ref:
            - matrix_inner_bottom
          shift: [kx/2 + 11, -ky/2 - 5]
          rotate: 0
        params:
          front: true
          back: true
          width: 1.5
          height: 1.5
          text: "B+"
          net: RAW
      pad_minus_l:
        what: pad
        where:
          ref:
            - matrix_inner_bottom
          shift: [kx/2 + 4 + 11, -ky/2 - 5]
          rotate: 0
        params:
          front: true
          back: true
          width: 1.5
          height: 1.5
          text: "B-"
          net: GND
      pad_plus_r:
        what: pad
        where:
          ref:
            - mirror_matrix_inner_bottom
          shift: [kx/2+11, -ky/2-5]
          rotate: 0
        params:
          front: true
          back: true
          width: 1.5
          height: 1.5
          text: "B+"
          net: mirror_RAW
      pad_minus_r:
        what: pad
        where:
          ref:
            - mirror_matrix_inner_bottom
          shift: [kx/2 + 4 + 11, -ky/2 - 5]
          rotate: 0
        params:
          front: true
          back: true
          width: 1.5
          height: 1.5
          text: "B-"
          net: mirror_GND
      # jumper_l:
      #   what: jumper
      #   where:
      #     ref:
      #       - matrix_inner_bottom
      #     shift: [23.5, 0]
      #     rotate: 270
      #   params:
      #     side: F
      #     from: BAT_POS
      #     to: RAW5V
      # jumper_r:
      #   what: jumper
      #   where:
      #     ref:
      #       - mirror_matrix_inner_bottom
      #     shift: [23.5, 0]
      #     rotate: 90
      #   params:
      #     side: F
      #     from: mirror_BAT_POS
      #     to: mirror_RAW5V
      slider_l:
        what: slider_threeway
        where:
          ref:
            - matrix_middle_top
          shift: [-2 kx, 0.25 ky]
          rotate: 0
        params:
          side: F
          from: RAW
          left: BAT_POS
          right: ''
      slider_r:
        what: slider_threeway
        where:
          ref:
            - mirror_matrix_middle_top
          shift: [-2 kx, 0.25 ky]
          rotate: 0
        params:
          side: F
          from: mirror_RAW
          left: ''
          right: mirror_BAT_POS
      reset_l:
        what: reset_button
        where:
          ref:
            - matrix_middle_top
          shift: [-2.75 kx, 0.25 ky]
          rotate: 0
        params:
          from: GND
          to: RST
      reset_r:
        what: reset_button
        where:
          ref:
            - mirror_matrix_middle_top
          shift: [-2.75 kx, 0.25 ky]
          rotate: 0
        params:
          from: mirror_GND
          to: mirror_RST
      info_l:
        what: text
        where:
          ref:
            - matrix_pinky_bottom
          shift: [0.75 kx, 0]
        params:
          text: "acinonyx v0.1\\nby stronglytyped"
          justify: left
      info_r:
        what: text
        where:
          ref:
            - matrix_pinky_bottom
          shift: [0.75 kx, 0]
        params:
          layer: B.SilkS
          text: "acinonyx v0.1\\nby stronglytyped"
          justify: right mirror
