units:
  # Size of each key. cx and cy for choc, u and U for MX.
  kx: cx
  ky: cy
  # key spread and padding
  px: 4
  py: 4
  # From that, get the spacing between keys
  brickw: 6.5 kx + px + 11
  brickh: 4.5 ky + py + 2
  brickx: 3
  bricky: -ky + 0

  xiao_length: 21
  xiao_width: 17.78

points:
  zones:
    matrix:
      anchor:
        shift: [100, -100]
      rotate: 10
      key.padding: ky
      columns:
        outer:
          key:
            stagger: 0 ky
            spread: kx
            column_net: P6
        pinky:
          key:
            stagger: 0 ky
            spread: kx
            column_net: P5
        ring:
          key:
            stagger: 0.5 ky
            spread: kx
            splay: -5
            origin: [-kx/2, -ky/2]
            column_net: P3
        middle:
          key:
            stagger: 0.2 ky
            spread: kx
            splay: -5
            origin: [-kx/2, -ky/2]
            column_net: P2
        index:
          key:
            stagger: -0.2 ky
            spread: kx
            column_net: P1
        inner:
          key:
            stagger: -0.1 ky
            spread: kx
            column_net: P0
      rows:
        bottom:
          row_net: P10
        home:
          row_net: P9
        top:
          row_net: P8
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-kx-kx/4, -1.1 ky]
        rotate: 4
      key:
        spread: kx
      columns:
        inner:
          key:
            splay: 0
            origin: [-0.5 kx, -0.5 ky]
            column_net: P2
        middle:
          key:
            splay: -17
            origin: [-0.5 kx, -0.5 ky]
            column_net: P1
        home:
          key:
            splay: -17
            origin: [-0.5 kx, -0.5 ky]
            column_net: P0
      rows:
        thumb:
          row_net: P4

outlines:
  # board dimensions according to JLCPCB: 122.28 mm x 101.05 mm
  raw:
    - what: rectangle
      where: true
      asym: source
      size: [kx + px, ky + py]
      corner: px
  thumbfan_glue:
    - what: polygon
      points:
        - ref: matrix_inner_bottom
          shift: [0.5 kx + 0.5px, -0.5 ky + 0.5 py]
        - ref: thumbfan_home_thumb
          shift: [0.5 kx - 0.5px, 0.5 ky + 0.5 py]
        - ref: thumbfan_home_thumb
          shift: [0.5 kx - 0.5px, -0.5 ky - 0.5 py]
        - ref: thumbfan_inner_thumb
          shift: [-0.5 kx + 0.5 px, -0.5 ky - 0.5 py]
        - ref: matrix_pinky_bottom
          shift: [0.5 kx - 0.5 py, -0.5 ky - 0.5 py]
        - ref: matrix_pinky_home
        - ref: matrix_inner_home
  patch_outer:
    - what: polygon
      points:
        - ref: matrix_ring_top
        - ref: matrix_ring_bottom
        - ref: matrix_pinky_bottom
          shift: [-0.5 (kx + px), 0]
        - ref: matrix_pinky_top
          shift: [-0.5 (kx + px), 0]
  patch_inner:
    - what: polygon
      points:
        - ref: matrix_inner_top
          shift: [0.5 (kx + px), 0]
        - ref: matrix_inner_bottom
          shift: [0.5 (kx + px), 0]
        - ref: matrix_index_bottom
        - ref: matrix_index_top
  patch_thumb:
    - what: polygon
      points:
        - ref: matrix_index_bottom
          shift: [0, -0.5 ky]
        - ref: thumbfan_home_thumb
          shift: [-0.5 kx, 0]
        - ref: matrix_inner_bottom
          shift: [-0.5 kx, -0.5 ky]
  controller_area:
    - what: rectangle
      where:
        - ref: matrix_inner_home
          # re-tranalte to new anchor position
          shift: [kx + 3, 0]
      size: [20, 17.5]
      corner: 4
  brick:
    - what: rectangle
      where:
        - ref: matrix_middle_home
          # re-tranalte to new anchor position
          shift: [brickx , bricky]
      size: [brickw, brickh]
      corner: 1
    # - what: rectangle
    #   where:
    #     - ref: mirror_matrix_middle_home
    #       # re-tranalte to new anchor position
    #       shift: [brickx , bricky]
    #   size: [brickw, brickh]
    #   corner: 1
  switches:
    - what: rectangle
      where: true
      asym: source
      size: 14
  keycaps:
    - what: rectangle 
      where: true
      asym: source
      size: [kx, ky] 
      corner: 1
  keywell:
    - "raw"
    #- "+patch_inner"
    #- "+patch_outer"
    #- "+thumbfan_glue"
  base_outline:
    - "keywell"
    - "+brick"
  screw_holes:
    top_left:
      what: circle
      where:
        - ref: matrix_outer_top
          shift: [0.2 kx, 1.3 ky]
      radius: 1.05
    bottom_left:
      what: circle
      where:
        - ref: matrix_outer_bottom
          shift: [-0.55 kx, -1.05 ky]
      radius: 1.05
    top_right:
      what: circle
      where:
        - ref: matrix_inner_top
          shift: [1.65 kx, 0.56 ky]
      radius: 1.05
    thumb:
      what: circle
      where:
        - ref: matrix_inner_bottom
          shift: [1.65 kx, -1.9 ky]
      radius: 1.05
    # mirror_top_left:
    #   what: circle
    #   where:
    #     - ref: mirror_matrix_outer_top
    #       shift: [0.2 kx, 1.3 ky]
    #   radius: 1.05
    # mirror_bottom_left:
    #   what: circle
    #   where:
    #     - ref: mirror_matrix_outer_bottom
    #       shift: [-0.55 kx, -1.05 ky]
    #   radius: 1.05
    # mirror_top_right:
    #   what: circle
    #   where:
    #     - ref: mirror_matrix_inner_top
    #       shift: [1.65 kx, 0.56 ky]
    #   radius: 1.05
    # mirror_thumb:
    #   what: circle
    #   where:
    #     - ref: mirror_matrix_inner_bottom
    #       shift: [1.65 kx, -1.9 ky]
    #   radius: 1.05
  mounting_holes:
    $extends: outlines.screw_holes
    top_left:
      radius: 2.05
    bottom_left:
      radius: 2.05
    top_right:
      radius: 2.05
    thumb:
      radius: 2.05
    # mirror_top_left:
    #   radius: 2.05
    # mirror_bottom_left:
    #   radius: 2.05
    # mirror_top_right:
    #   radius: 2.05
    # mirror_thumb:
    #   radius: 2.05
  bottom_outline:
    - "base_outline"
    # TODO use footprints with pad + via reinforcement as mounting holes
    - "-screw_holes"
  plate:
    - "keywell"
    - "brick"
    - "+patch_thumb"
    #- "-controller_area"
    #- "-keycaps"
    - "-switches"
    - "-screw_holes"
  pcb:
    - "base_outline"
    # TODO use footprints with pad + via reinforcement as mounting holes
    - "-mounting_holes"

pcbs:
  board:
    outlines:
      edge:
        outline: pcb
        layer: Edge.Cuts
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      diode:
        what: pad_diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -0.3ky]
      diode_via_1:
        what: via
        where: true
        params:
          net: "{{colrow}}"
        adjust:
          shift: [2.8, -0.3ky]
      diode_via_2:
        what: via
        where: true
        params:
          net: "{{row_net}}"
        adjust:
          shift: [-2.8, -0.3ky]
      key_via_1:
        what: via
        where: true
        params:
          net: "{{column_net}}"
        adjust:
          shift: [0, 3.67]
      key_via_2:
        what: via
        where: true
        params:
          net: "{{colrow}}"
        adjust:
          shift: [0, 2.67]
      xiao_flippable:
        what: xiao_flippable
        where:
          ref: matrix_inner_top
          shift: [0.5kx-(kx-xiao_width)/2 + 3, 0.5 ky - xiao_length - 3]
          rotate: -90
      raw_pad:
        what: pad
        where:
          ref: matrix_inner_top
          shift: [0.5kx-(kx-xiao_width)/2 + 3 + xiao_width/2, 0.5 ky - xiao_length - 3]
        params:
          net: RAW
          width: 1.5
          height: 1.5
      battery_pads:
        what: battery_pad
        where:
          ref: matrix_inner_top
          shift: [0.5kx-(kx-xiao_width)/2 + 3 + xiao_width/2, 0.5 ky - xiao_length - 3 - 0.1ky]
          rotate: 0
        params:
          plus: BAT+
          minus: GND
      slider_f:
        what: slider
        where:
          ref: matrix_pinky_top
          shift: [0, 1.25 ky]
          rotate: -10
        params:
          from: BAT+
          to: RAW
          side: F
      slider_b:
        what: slider
        where:
          ref: matrix_pinky_top
          shift: [0, 1.25 ky]
          rotate: -10
        params:
          from: BAT+
          to: RAW
          side: B
  top_plate:
    outlines:
      edge:
        outline: plate
        layer: Edge.Cuts
    footprints:
      jlc_order_number:
        what: text
        where:
          ref:
            - matrix_ring_home
          shift: [-0.25 kx, 0.5 ky]
        params:
          text: "JLCJLCJLCJLC"
          justify: left
  bottom_plate:
    outlines:
      edge:
        outline: bottom_outline
        layer: Edge.Cuts
  